### ISSUE TITLE
Error is displayed in extension

### ISSUE THREAD

**Issue by aadibajpai** [SwagLyrics/SwagLyrics-Chrome-Extension#5]
![image](https://user-images.githubusercontent.com/27063113/73183486-df66f380-4140-11ea-8221-67f86992a576.png)
Needs taken care of so we move forward with publishing it on Chrome

**Comment by flabbet** [comment]
Should be good now

**Comment by aadibajpai** [comment]
![image](https://user-images.githubusercontent.com/27063113/73237818-d3b91280-41bc-11ea-8e1c-6de00d248694.png)
@flabbet

**Comment by aadibajpai** [comment]
the extension works but that error persists

**Comment by flabbet** [comment]
Should be gone now, but please check

**Comment by aadibajpai** [comment]
Don't get it anymore
