### ISSUE TITLE
Doesn't work if the Spotify Web Player tab is not open

### ISSUE THREAD

**Issue by aadibajpai** [SwagLyrics/SwagLyrics-Chrome-Extension#6]
It should work as long as the web player is working, and not just when the Spotify Web Player is the active tab.

**Comment by flabbet** [comment]
Bug exists when Spotify Web Player is controlled by other device and tab minimized. SwSpotify recieves ping, but not `getSong`. Reason and fix currently unknown.

**Comment by aadibajpai** [comment]
https://cdn.discordapp.com/attachments/666773451385733151/673215932692168734/2020-02-01_22-47-52.flv

Video that shows how the song updated when I made the Web Player the active tab, until then it was only responding with the previous song, artist pair.
